# Generated by Django 3.2.8 on 2021-10-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='api_token',
            field=models.CharField(max_length=70, unique=True),
        ),
    ]
