# Generated by Django 3.2.8 on 2021-10-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
