# Generated by Django 3.2.8 on 2021-10-24 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='description',
        ),
    ]
